name: Build and Publish EPUB

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Book slug'
        required: true
        type: string
      payload:
        description: 'URL to fetch the book payload'
        required: true
        type: string
      token:
        description: 'Authentication token'
        required: true
        type: string

env:
  NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL || 'https://your-app-url.com' }}
  NEXT_EPUB_SECRET: ${{ secrets.NEXT_EPUB_SECRET }}

jobs:
  build-epub:
    name: Build EPUB
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch book data
        id: fetch-book
        env:
          AUTH_TOKEN: ${{ github.event.inputs.token }}
        run: |
          echo "Fetching book data from ${{ github.event.inputs.payload }}"
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ github.event.inputs.token }}" "${{ github.event.inputs.payload }}")
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
          
          # Extract the download URL from the response
          DOWNLOAD_URL=$(echo "$RESPONSE" | jq -r '.download_url // empty')
          if [ -z "$DOWNLOAD_URL" ]; then
            echo "No download URL found in response"
            exit 1
          fi
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

      - name: Download book content
        run: |
          mkdir -p ./book-content
          curl -H "Authorization: Bearer ${{ github.event.inputs.token }}" -L "${{ steps.fetch-book.outputs.download_url }}" -o ./book-content/book.json

      - name: Generate EPUB
        run: |
          echo "Generating EPUB for ${{ github.event.inputs.slug }}"
          # Add your EPUB generation command here
          # Example: node scripts/generate-epub.js ./book-content/book.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: epub-file
          path: ./output/*.epub
          retention-days: 1
